"""Shared optimization infrastructure; algorithms remain intentionally absent."""

from optimization.constraints import (
    LOWER_BOUNDS,
    PARAMETER_COUNT,
    PARAMETER_DEFINITIONS,
    PARAMETER_NAMES,
    UPPER_BOUNDS,
    ConstraintViolation,
    ParameterDefinition,
    constraint_violations,
    invalid_reasons,
    is_physically_valid,
    lower_bounds,
    upper_bounds,
    validate_parameter_vector,
    validate_physical_parameters,
)
from optimization.objective import (
    InvalidParameterError,
    ObjectiveEvaluator,
    ObjectiveResult,
    calculate_error_components,
    evaluate,
    objective,
)
from optimization.parameterization import (
    DELTA_N,
    INDEX_LOWER_BOUND,
    INDEX_UPPER_BOUND,
    NORMALIZED_PARAMETER_COUNT,
    to_normalized,
    to_physical,
    validate_normalized,
)
from optimization.random_search import ConvergenceRecord, RandomSearchResult, random_search
from optimization.differential_evolution import (
    DEFAULT_CONFIGURATION,
    NORMALIZED_BOUNDS,
    DifferentialEvolutionConfiguration,
    DifferentialEvolutionConvergenceRecord,
    DifferentialEvolutionResult,
    differential_evolution,
)
from optimization.genetic_algorithm import (
    DEFAULT_CONFIGURATION as DEFAULT_GA_CONFIGURATION,
    GeneticAlgorithmConfiguration,
    GeneticAlgorithmConvergenceRecord,
    GeneticAlgorithmResult,
    genetic_algorithm,
)

__all__ = [
    "LOWER_BOUNDS",
    "PARAMETER_COUNT",
    "PARAMETER_DEFINITIONS",
    "PARAMETER_NAMES",
    "UPPER_BOUNDS",
    "ConstraintViolation",
    "ParameterDefinition",
    "constraint_violations",
    "invalid_reasons",
    "is_physically_valid",
    "lower_bounds",
    "upper_bounds",
    "validate_parameter_vector",
    "validate_physical_parameters",
    "InvalidParameterError",
    "ObjectiveEvaluator",
    "ObjectiveResult",
    "calculate_error_components",
    "evaluate",
    "objective",
    "DELTA_N",
    "INDEX_LOWER_BOUND",
    "INDEX_UPPER_BOUND",
    "NORMALIZED_PARAMETER_COUNT",
    "to_normalized",
    "to_physical",
    "validate_normalized",
    "ConvergenceRecord",
    "RandomSearchResult",
    "random_search",
    "DEFAULT_CONFIGURATION",
    "NORMALIZED_BOUNDS",
    "DifferentialEvolutionConfiguration",
    "DifferentialEvolutionConvergenceRecord",
    "DifferentialEvolutionResult",
    "differential_evolution",
    "DEFAULT_GA_CONFIGURATION",
    "GeneticAlgorithmConfiguration",
    "GeneticAlgorithmConvergenceRecord",
    "GeneticAlgorithmResult",
    "genetic_algorithm",
]
